export const MYANMAR_CITIES = [
  "Yangon",
  "Mandalay",
  "Naypyidaw",
  "Mawlamyine",
  "Bago",
  "Pathein",
  "Taunggyi",
  "Monywa",
  "Myitkyina",
  "Lashio",
  "Pyin Oo Lwin",
  "Sittwe",
  "Pyay",
  "Kalay",
  "Myawaddy",
  "Pakokku",
  "Myeik",
  "Meiktila",
  "Taungoo",
  "Myingyan",
  "Mogok",
  "Taikkyi",
  "Magway",
  "Hinthada",
  "Sagaing",
  "Thanlyin",
  "Hpa-An",
  "Muse",
  "Dawei",
  "Nyaunglebin",
  "Shwebo",
  "Pyinmana",
  "Pyu",
  "Hpakant",
  "Myaungmya",
  "Shwegu",
  "Kawthaung",
  "Kalaw",
  "Thanbyuzayat",
  "Thaton",
  "Ann",
  "Aunglan",
  "Aungpan",
  "Ayadaw",
  "Ayetharyar",
  "Bhamo",
  "Mudon",
  "Yenangyaung",
  "Taungdwingyi",
  "Bogale",
  "Pyapon",
  "Yamethin",
  "Kyonpyaw",
  "Aungban",
  "Mohnyin",
  "Waingmaw",
  "Kyaikto",
  "Myanaung",
  "Kyaukse",
  "Tachilek",
  "Hakha",
  "Loikaw",
  "Letpandan",
  "Wakema",
  "Chauk",
  "Minbu",
  "Thayetmyo",
  "Kanbe",
  "Maubin",
  "Kyaiklat",
  "Thongwa",
  "Twante",
  "Nyaungdon",
  "Paungde",
].sort();

export function findMatchingCities(query: string, limit: number = 5): string[] {
  if (!query) return [];

  const lowerQuery = query.toLowerCase();

  return MYANMAR_CITIES.filter((city) =>
    city.toLowerCase().includes(lowerQuery)
  ).slice(0, limit);
}

export function isCityInList(city: string): boolean {
  return MYANMAR_CITIES.some((c) => c.toLowerCase() === city.toLowerCase());
}
