import { Document, Page, Text, View } from "@react-pdf/renderer";
import { ExtractedData } from "@/types/invoice";
import { StoreInfo } from "@/components/organisms/StoreSettings";
import { pdfStyles } from "@/lib/pdfStyles";

interface InvoicePDFDocumentProps {
  data: ExtractedData;
  storeInfo: StoreInfo;
}

export default function InvoicePDFDocument({
  data,
  storeInfo,
}: InvoicePDFDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        {/* Header */}
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.logo}>{storeInfo.name || "OrderKyat"}</Text>
          <Text style={pdfStyles.storeInfo}>
            {storeInfo.phone || "+95 9 123 456 789"}
          </Text>
          <Text style={pdfStyles.storeInfo}>
            {storeInfo.address || "Yangon, Myanmar"}
          </Text>
        </View>

        {/* Title */}
        <Text style={pdfStyles.title}>INVOICE</Text>
        <Text style={{ ...pdfStyles.text, textAlign: "right", fontSize: 9 }}>
          Date:{" "}
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </Text>

        {/* Bill To */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>Bill To:</Text>
          <Text style={pdfStyles.text}>{data.customerName}</Text>
          <Text style={pdfStyles.text}>{data.phone}</Text>
          <Text style={pdfStyles.text}>{data.address}</Text>
        </View>

        {/* Items Table */}
        <View style={pdfStyles.table}>
          <View style={pdfStyles.tableHeader}>
            <Text style={pdfStyles.col1}>Item</Text>
            <Text style={pdfStyles.col2}>Qty</Text>
            <Text style={pdfStyles.col3}>Price</Text>
            <Text style={pdfStyles.col4}>Total</Text>
          </View>

          {data.items.map((item, index) => (
            <View key={index} style={pdfStyles.tableRow}>
              <Text style={pdfStyles.col1}>{item.name}</Text>
              <Text style={pdfStyles.col2}>{item.quantity}</Text>
              <Text style={pdfStyles.col3}>
                {item.price.toLocaleString()} Ks
              </Text>
              <Text style={pdfStyles.col4}>
                {(item.quantity * item.price).toLocaleString()} Ks
              </Text>
            </View>
          ))}
        </View>

        {/* Total */}
        <View style={pdfStyles.total}>
          <Text style={pdfStyles.totalText}>
            Total: {data.totalPrice.toLocaleString()} Ks
          </Text>
        </View>

        {/* Footer */}
        <View style={pdfStyles.footer}>
          <Text>Thank you for your business!</Text>
          <Text>
            Generated by OrderKyat - Myanmar&apos;s Smart Invoice Generator 🇲🇲
          </Text>
        </View>
      </Page>
    </Document>
  );
}
