import { Document, Page, Text, View } from "@react-pdf/renderer";
import { ExtractedData } from "@/types/invoice";
import { StoreInfo } from "@/components/organisms/StoreSettings";
import { pdfStyles } from "@/lib/pdfStyles";

interface InvoicePDFDocumentProps {
  data: ExtractedData;
  storeInfo: StoreInfo;
}

export default function InvoicePDFDocument({
  data,
  storeInfo,
}: InvoicePDFDocumentProps) {
  // ✅ Calculate totals
  const subtotal = data.items.reduce(
    (sum, item) => sum + item.quantity * item.price,
    0
  );
  const deliveryFee = data.deliveryFee || 0;
  const grandTotal = subtotal + deliveryFee;

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        {/* Header */}
        <View style={pdfStyles.header}>
          <Text style={pdfStyles.logo}>{storeInfo.name || "OrderKyat"}</Text>
          <Text style={pdfStyles.storeInfo}>
            {storeInfo.phone || "+95 9 123 456 789"}
          </Text>
          <Text style={pdfStyles.storeInfo}>
            {storeInfo.address || "Yangon, Myanmar"}
          </Text>
        </View>

        {/* Title */}
        <Text style={pdfStyles.title}>INVOICE</Text>
        <Text style={{ ...pdfStyles.text, textAlign: "right", fontSize: 9 }}>
          Date:{" "}
          {new Date().toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          })}
        </Text>

        {/* Bill To */}
        <View style={pdfStyles.section}>
          <Text style={pdfStyles.sectionTitle}>Bill To:</Text>
          <Text style={pdfStyles.text}>{data.customerName}</Text>
          <Text style={pdfStyles.text}>{data.phone}</Text>
          {data.address && <Text style={pdfStyles.text}>{data.address}</Text>}
        </View>

        {/* ✅ NEW: Delivery Information */}
        {(data.deliveryType ||
          (data.deliveryFee !== undefined && data.deliveryFee >= 0)) && (
          <View style={pdfStyles.deliverySection}>
            <Text style={pdfStyles.deliveryTitle}>🚚 Delivery Information</Text>
            {data.deliveryType && (
              <Text style={pdfStyles.deliveryText}>
                Type: {data.deliveryType}
              </Text>
            )}
            {data.deliveryFee !== undefined && (
              <Text style={pdfStyles.deliveryText}>
                Delivery Fee: {data.deliveryFee.toLocaleString()} Ks
              </Text>
            )}
          </View>
        )}

        {/* Items Table */}
        <View style={pdfStyles.table}>
          <View style={pdfStyles.tableHeader}>
            <Text style={pdfStyles.col1}>Item</Text>
            <Text style={pdfStyles.col2}>Qty</Text>
            <Text style={pdfStyles.col3}>Price</Text>
            <Text style={pdfStyles.col4}>Total</Text>
          </View>

          {data.items.map((item, index) => (
            <View key={index} style={pdfStyles.tableRow}>
              <Text style={pdfStyles.col1}>{item.name}</Text>
              <Text style={pdfStyles.col2}>{item.quantity}</Text>
              <Text style={pdfStyles.col3}>
                {item.price.toLocaleString()} Ks
              </Text>
              <Text style={pdfStyles.col4}>
                {(item.quantity * item.price).toLocaleString()} Ks
              </Text>
            </View>
          ))}
        </View>

        {/* ✅ NEW: Summary Section (Subtotal, Delivery, Total) */}
        <View style={pdfStyles.summarySection}>
          {/* Subtotal */}
          <View style={pdfStyles.summaryRow}>
            <Text style={pdfStyles.summaryLabel}>Subtotal:</Text>
            <Text style={pdfStyles.summaryValue}>
              {subtotal.toLocaleString()} Ks
            </Text>
          </View>

          {/* Delivery Fee (only show if > 0) */}
          {deliveryFee > 0 && (
            <View style={pdfStyles.summaryDeliveryRow}>
              <Text style={pdfStyles.summaryDeliveryLabel}>
                🚚 Delivery Fee:
              </Text>
              <Text style={pdfStyles.summaryDeliveryValue}>
                {deliveryFee.toLocaleString()} Ks
              </Text>
            </View>
          )}

          {/* Grand Total */}
          <View style={pdfStyles.total}>
            <Text style={pdfStyles.totalLabel}>Total Amount:</Text>
            <Text style={pdfStyles.totalText}>
              {grandTotal.toLocaleString()} Ks
            </Text>
          </View>
        </View>

        {/* Footer */}
        <View style={pdfStyles.footer}>
          <Text>Thank you for your business!</Text>
          <Text>
            Generated by OrderKyat - Myanmar&apos;s Smart Invoice Generator 🇲🇲
          </Text>
        </View>
      </Page>
    </Document>
  );
}
