"use client";

import { useState, useMemo } from "react";

import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFViewer,
  PDFDownloadLink,
} from "@react-pdf/renderer";
import { ExtractedData } from "@/types/invoice";
import { StoreInfo } from "./StoreSettings";
import { Download, ZoomIn, ZoomOut, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import PageHeader from "@/components/organisms/PageHeader";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: "#ffffff",
  },
  header: {
    marginBottom: 20,
    borderBottom: "2px solid #10b981",
    paddingBottom: 15,
  },
  logo: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#10b981",
    marginBottom: 5,
  },
  storeInfo: {
    fontSize: 10,
    color: "#64748b",
    marginTop: 3,
  },
  title: {
    fontSize: 24,
    textAlign: "center",
    marginBottom: 10,
    color: "#1e293b",
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#475569",
    textTransform: "uppercase",
  },
  text: {
    fontSize: 11,
    marginBottom: 4,
    color: "#334155",
  },
  table: {
    marginTop: 15,
    marginBottom: 15,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f1f5f9",
    padding: 8,
    fontSize: 10,
    fontWeight: "bold",
    color: "#475569",
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "1px solid #e2e8f0",
    padding: 8,
    fontSize: 10,
  },
  col1: { width: "50%" },
  col2: { width: "15%", textAlign: "center" },
  col3: { width: "20%", textAlign: "right" },
  col4: { width: "15%", textAlign: "right" },
  total: {
    marginTop: 20,
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingTop: 15,
    borderTop: "2px solid #10b981",
  },
  totalText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#10b981",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 9,
    color: "#94a3b8",
    borderTop: "1px solid #e2e8f0",
    paddingTop: 10,
  },
});

interface InvoicePDFPreviewProps {
  data: ExtractedData;
  storeInfo: StoreInfo;
  onBack?: () => void;
}

const InvoicePDFDocument = ({ data, storeInfo }: InvoicePDFPreviewProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header with Store Info */}
      <View style={styles.header}>
        <Text style={styles.logo}>{storeInfo.name || "OrderKyat"}</Text>
        <Text style={styles.storeInfo}>
          {storeInfo.phone || "+95 9 123 456 789"}
        </Text>
        <Text style={styles.storeInfo}>
          {storeInfo.address || "Yangon, Myanmar"}
        </Text>
      </View>

      {/* Title */}
      <Text style={styles.title}>INVOICE</Text>
      <Text style={{ ...styles.text, textAlign: "right", fontSize: 9 }}>
        Date:{" "}
        {new Date().toLocaleDateString("en-US", {
          year: "numeric",
          month: "long",
          day: "numeric",
        })}
      </Text>

      {/* Customer Info */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Bill To:</Text>
        <Text style={styles.text}>{data.customerName}</Text>
        <Text style={styles.text}>{data.phone}</Text>
        <Text style={styles.text}>{data.address}</Text>
      </View>

      {/* Items Table */}
      <View style={styles.table}>
        <View style={styles.tableHeader}>
          <Text style={styles.col1}>Item</Text>
          <Text style={styles.col2}>Qty</Text>
          <Text style={styles.col3}>Price</Text>
          <Text style={styles.col4}>Total</Text>
        </View>

        {data.items.map((item, index) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.col1}>{item.name}</Text>
            <Text style={styles.col2}>{item.quantity}</Text>
            <Text style={styles.col3}>{item.price.toLocaleString()} Ks</Text>
            <Text style={styles.col4}>
              {(item.quantity * item.price).toLocaleString()} Ks
            </Text>
          </View>
        ))}
      </View>

      {/* Total */}
      <View style={styles.total}>
        <Text style={styles.totalText}>
          Total: {data.totalPrice.toLocaleString()} Ks
        </Text>
      </View>

      {/* Footer */}
      <View style={styles.footer}>
        <Text>Thank you for your business!</Text>
        <Text>
          Generated by OrderKyat - Myanmar&apos;s Smart Invoice Generator 🇲🇲
        </Text>
      </View>
    </Page>
  </Document>
);

// ✅ Helper functions
const getInitials = (name: string): string => {
  return name
    .split(/\s+/)
    .map((word) => word.charAt(0).toUpperCase())
    .join("");
};

const formatDate = (timestamp: number): string => {
  const date = new Date(timestamp);
  const year = date.getFullYear().toString().slice(-2);
  const month = (date.getMonth() + 1).toString().padStart(2, "0");
  const day = date.getDate().toString().padStart(2, "0");
  return `${year}${month}${day}`;
};

export default function InvoicePDFPreview({
  data,
  storeInfo,
  onBack,
}: InvoicePDFPreviewProps) {
  const [scale, setScale] = useState(1);
  const [timestamp] = useState(() => Date.now());

  const fileName = useMemo(() => {
    const storeInitials = getInitials(storeInfo.name || "OrderKyat");
    const customerInitials = getInitials(data.customerName || "Customer");
    const dateStr = formatDate(timestamp);
    return `INV-${storeInitials}-${customerInitials}-${dateStr}.pdf`;
  }, [data.customerName, storeInfo.name, timestamp]);

  return (
    <div className="flex flex-col h-screen">
      {/* ✅ Header - Hide Download button on mobile */}
      <PageHeader
        showBack={true}
        onBack={onBack}
        icon={FileText}
        title="PDF Preview"
        subtitle="Review before downloading"
        hideMobileActions={true} // ✅ Hide download button on mobile
        actions={
          <>
            {/* Zoom Controls - Desktop only */}
            <div className="hidden md:flex items-center gap-1 bg-slate-100 rounded-lg p-1">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setScale((s) => Math.max(0.5, s - 0.1))}
                disabled={scale <= 0.5}
                className="h-8 px-2 hover:bg-white"
              >
                <ZoomOut className="w-3.5 h-3.5" />
              </Button>
              <span className="text-xs font-medium text-slate-700 px-2 min-w-[50px] text-center">
                {Math.round(scale * 100)}%
              </span>
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setScale((s) => Math.min(2, s + 0.1))}
                disabled={scale >= 2}
                className="h-8 px-2 hover:bg-white"
              >
                <ZoomIn className="w-3.5 h-3.5" />
              </Button>
            </div>

            {/* ✅ Download Button - Desktop only */}
            <PDFDownloadLink
              document={
                <InvoicePDFDocument data={data} storeInfo={storeInfo} />
              }
              fileName={fileName}
              className="hidden sm:inline-flex" // ✅ Hide on mobile
            >
              {({ loading }) => (
                <Button
                  size="sm"
                  className="bg-green-600 hover:bg-green-700 gap-1.5 shadow-sm h-8 sm:h-9"
                  disabled={loading}
                >
                  <Download className="w-3.5 h-3.5" />
                  <span className="text-sm">
                    {loading ? "Preparing..." : "Download PDF"}
                  </span>
                </Button>
              )}
            </PDFDownloadLink>
          </>
        }
      />

      {/* ✅ PDF Preview Area - With bottom padding for mobile button */}
      <div className="flex-1 bg-slate-100 overflow-auto pb-20 sm:pb-0">
        <div className="min-h-full flex items-start justify-center p-4 md:p-8">
          {/* Desktop: Full PDF Viewer */}
          <div className="hidden md:block w-full max-w-4xl">
            <div
              className="bg-white shadow-2xl rounded-lg overflow-hidden"
              style={{
                transform: `scale(${scale})`,
                transformOrigin: "top center",
                transition: "transform 0.2s ease-out",
              }}
            >
              <PDFViewer
                width="100%"
                height="842px"
                showToolbar={false}
                className="border-0"
              >
                <InvoicePDFDocument data={data} storeInfo={storeInfo} />
              </PDFViewer>
            </div>
          </div>

          {/* Mobile: Summary Card */}
          <div className="md:hidden w-full max-w-md">
            <div className="bg-white rounded-lg shadow-lg p-6 space-y-6">
              <div className="text-center">
                <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Download className="w-8 h-8 text-green-600" />
                </div>
                <h3 className="text-xl font-bold text-slate-900 mb-2">
                  Invoice Ready!
                </h3>
                <p className="text-sm text-slate-600">
                  Your invoice has been generated successfully
                </p>
              </div>

              {/* Invoice Summary */}
              <div className="border border-slate-200 rounded-lg p-4 space-y-3">
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Store:</span>
                  <span className="font-medium text-slate-900">
                    {storeInfo.name || "OrderKyat"}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Customer:</span>
                  <span className="font-medium text-slate-900">
                    {data.customerName}
                  </span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-slate-600">Items:</span>
                  <span className="font-medium text-slate-900">
                    {data.items.length}
                  </span>
                </div>
                <div className="flex justify-between text-lg font-bold pt-3 border-t border-slate-200">
                  <span className="text-slate-900">Total:</span>
                  <span className="text-green-600">
                    {data.totalPrice.toLocaleString()} Ks
                  </span>
                </div>
              </div>

              <p className="text-xs text-center text-slate-500">
                💡 Preview is available on desktop devices
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* ✅ Fixed Mobile Download Button - Outside content area */}
      <div className="fixed bottom-0 left-0 right-0 sm:hidden bg-white border-t border-slate-200 p-3 shadow-lg z-20">
        <PDFDownloadLink
          document={<InvoicePDFDocument data={data} storeInfo={storeInfo} />}
          fileName={fileName}
        >
          {({ loading }) => (
            <Button
              className="w-full bg-green-600 hover:bg-green-700 h-12 text-base gap-2"
              disabled={loading}
            >
              <Download className="w-5 h-5" />
              {loading ? "Preparing PDF..." : "Download Invoice"}
            </Button>
          )}
        </PDFDownloadLink>
      </div>
    </div>
  );
}

export { InvoicePDFDocument };
